### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Haru-Im** [TheON2/TodoList#3]
도원님 안녕하세요! 코드 인상깊게 잘 봤습니다!

일단 컴포넌트별로 명확한 역할이 있어 가독성이 좋고 재사용성도 좋아보이는 점이 좋았습니다.
또한 커스텀 훅을 사용하셔서 로직의 반복을 피하신 점도 정말 좋았습니다.
전체적으로 깔끔하고 일관적으로 작성된 코드라는 느낌을 받았습니다.

제가 부족하지만 약간의 이슈를 남겨드리자면,

1. **투두 아이템의 ID 생성**: 현재 코드에서는 새로운 투두 아이템의 ID를 생성하기 위해 todos.length + 1를 사용하고 있습니다. 이 방법은 투두 아이템을 삭제하고 새로운 아이템을 추가할 때 동일한 ID를 가진 아이템이 생성될 수 있습니다. 이를 방지하기 위해 고유한 ID를 생성하는 다른 방법을 고려할 수 있겠는데, 예를 들어, Date.now(), UUID 등을 사용할 수 있어 보입니다.

2. **훅 사용의 일관성**: 코드의 일관성을 위해, todos와 setTodos에 대한 state 설정도 useInput과 유사한 커스텀 훅을 만들어 사용할 수 있어 보입니다. 예를 들어, 투두 리스트의 추가, 삭제, 업데이트 로직을 묶은 useTodos와 같은 커스텀 훅을 만들 수 있지 않을까 싶습니다.

1레벨 과제 너무 수고 많으셨습니다!

**Comment by TheON2** [comment]
넵 감사합니다 피드백을 수용하여 리팩토링 해볼게요~ ㅎㅎ
